import 'package:flutter/material.dart';

final List<Color> tagsColors = [
  const Color.fromRGBO(0, 70, 122, 1),
  const Color.fromRGBO(106, 77, 217, 1),
  const Color.fromRGBO(139, 0, 9104, 1),
  const Color.fromRGBO(166, 0, 2, 1),
  const Color.fromRGBO(112, 29, 0, 1),
  const Color.fromRGBO(42, 31, 1, 1),
  const Color.fromRGBO(0, 69, 0, 1),
];


/// Names for the [TagSelect] page
final List<String> tagsNames = [
  "Choose Your Own Tag",
  "Art",
  "Writing",
  "Books & Libraries",
  "Streaming",
  "Positivity",
  "Aesthetic",
  "Television",
  "Funny",
  "Gaming",
  "Movies",
  "Music",
  "Comics",
  "Fashion",
  "Celebrities",
  "Illustration",
  "Beauty",
  "Kpop",
  "Anime",
  "Black Stories",
  "Animals",
  "Travel",
  "Computer Science",
  "Design",
  "Photography",
  "Architecture",
  "Autos",
  "Business",
  "DIY",
  "Education",
  "Food",
  "Health and Fitness",
  "Home and Lifestyle",
  "Museums",
  "History",
  "Parenting",
  "Nature",
  "Science",
  "Sports",
  "Nonprofit",
  "Quotes",
  "Politics",
  "Spirituality",
  "Technology",
];
