import 'package:flutter/material.dart';

final List<Color> tagsColors = [
  const Color.fromRGBO(0, 184, 184, 1),
  const Color.fromRGBO(124, 92, 92, 1),
  const Color.fromRGBO(255, 98, 98, 1),
  const Color.fromRGBO(255, 73, 73, 1),
  const Color.fromRGBO(255, 138, 138, 1),
  const Color.fromRGBO(232, 215, 215, 1),
  const Color.fromRGBO(0, 207, 207, 1),
];

final List<String> tagsNames = [
  "Choose Your Own Tag",
  "Trending",
  "Art",
  "Writing",
  "Books & Libraries",
  "Streaming",
  "Positivity",
  "Aesthetic",
  "Television",
  "Funny",
  "Gaming",
  "Movies",
  "Music",
  "Comics",
  "Fashion",
  "Celebrities",
  "Illustration",
  "Beauty",
  "Kpop",
  "Anime",
  "Black Stories",
  "Animals",
  "Travel",
  "Computer Science",
  "Design",
  "Photography",
  "Architecture",
  "Autos",
  "Business",
  "DIY",
  "Education",
  "Food",
  "Health and Fitness",
  "Home and Lifestyle",
  "Museums",
  "History",
  "Parenting",
  "Nature",
  "Science",
  "Sports",
  "Nonprofit",
  "Quotes",
  "Politics",
  "Spirituality",
  "Technology",
];
